# Generated by Django 5.1.4 on 2025-01-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='Enter the project link', null=True),
        ),
    ]
