# Generated by Django 5.1.4 on 2024-12-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToutubeVideo',
            new_name='YoutubeVideo',
        ),
    ]
